# Setup
setup: multi_task

# Database
train_db_name: NYUD
val_db_name: NYUD 
trBatch: 4
valBatch: 4
nworkers: 4

# Optimizer and scheduler
epochs: 100
optimizer: adamw
optimizer_kwargs:
   lr: 0.00005
   weight_decay: 0.0001
scheduler: poly

# Model
model: MTFormer_nyud
backbone: swim_transformer2
backbone_kwargs:
   pretrained: True
   dilated: False
head: deeplab2

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True

# Loss kwargs
loss_kwargs:
   loss_scheme: baseline_uncertainty
   loss_weights:
       semseg: 1.0
       depth: 1.0
